resolver 127.0.0.11 valid=30s ipv6=off;

map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server {
    listen 80;
    server_name _;
    sendfile on;
    client_max_body_size 40M;
    client_body_buffer_size 40M;

    location / {
        rewrite ^/(.*)$ /webprotege/$1 break;
        set $upstream http://webprotege-gwt-ui-server:8080;
        proxy_pass $upstream;
        proxy_set_header   Host $http_host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Host  $host;
        proxy_set_header   X-Forwarded-Server  $host;
        proxy_set_header   X-Forwarded-Port  $server_port;
        proxy_set_header   X-Forwarded-Proto $scheme;
        client_max_body_size   500m;
    }

    location /webprotege/ {
        set $upstream http://webprotege-gwt-ui-server:8080;
        proxy_pass $upstream;
        proxy_set_header   Host $http_host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Host  $host;
        proxy_set_header   X-Forwarded-Server  $host;
        proxy_set_header   X-Forwarded-Port  $server_port;
        proxy_set_header   X-Forwarded-Proto $scheme;
        client_max_body_size   500m;
    }

    location /files/submit {
        set $upstream http://webprotege-gwt-api-gateway:7777;
        proxy_pass $upstream;
        proxy_set_header   Host $http_host;
        client_max_body_size   500m;
    }

    location /data/ {
        set $upstream http://webprotege-gwt-api-gateway:7777;
        proxy_pass $upstream;
        proxy_set_header   Host $http_host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Host  $host;
        proxy_set_header   X-Forwarded-Server  $host;
        proxy_set_header   X-Forwarded-Port  $server_port;
        proxy_set_header   X-Forwarded-Proto $scheme;
        client_max_body_size   500m;
        rewrite_log on;
    }

    location /keycloak/ {
        set $upstream http://webprotege-keycloak:8080;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_redirect off;
    }

    location /wsapps {
        set $upstream http://webprotege-gwt-api-gateway:7777;
        proxy_pass $upstream;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    location /kibana/ {
        set $upstream http://kibana:5601;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_redirect off;
        proxy_buffering off;
        proxy_read_timeout 300;
        proxy_connect_timeout 300;
        proxy_send_timeout 300;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Prefix /kibana;
    }
}
