name: Update Compose File

on:
  repository_dispatch:
    types: [update_compose]

jobs:
  update-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all branches are fetched

      - name: Checkout target branch
        run: |
          BRANCH="${{ github.event.client_payload.branch }}"
          echo "Checking out branch: $BRANCH"

          # Check if branch exists locally or remotely
          if git ls-remote --exit-code --heads origin "$BRANCH"; then
            git checkout "$BRANCH"
          else
            echo "Branch '$BRANCH' does not exist. Exiting."
            exit 1
          fi

      - name: Update docker-compose image tag
        run: |
          SERVICE="${{ github.event.client_payload.service }}"
          VERSION="${{ github.event.client_payload.version }}"
          FILE=docker-compose.yml

          echo "Updating service '$SERVICE' to version '$VERSION' in $FILE"

          sed -i "s|\(image: protegeproject/$SERVICE:\)[^[:space:]]*|\1$VERSION|" "$FILE"

          grep "image: protegeproject/$SERVICE" "$FILE" || echo "No matching image line found."

      - name: Commit and push changes
        run: |
          git config user.name "who-icatx-bot"
          git config user.email "who-icatx-bot@users.noreply.github.com"

          git add docker-compose.yml
          git commit -m "chore: bump ${{ github.event.client_payload.service }} to ${{ github.event.client_payload.version }}"
          git push origin HEAD
