name: Update Compose File

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      version:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  update-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update docker-compose image tag
        run: |
          SERVICE="${{ inputs.service }}"
          VERSION="${{ inputs.version }}"
          FILE=docker-compose.yml

          echo "Updating service '$SERVICE' to version '$VERSION' in $FILE"

          sed -i "s|\(image: protegeproject/$SERVICE:\)[^[:space:]]*|\1$VERSION|" "$FILE"

          echo "Result:"
          grep "image: protegeproject/$SERVICE" "$FILE" || echo "No matching image line found."

      - name: Commit and push changes
        run: |
          git config user.name "who-icatx-bot"
          git config user.email "who-icatx-bot@users.noreply.github.com"

          git add docker-compose.yml
          git commit -m "chore: bump ${{ inputs.service }} to ${{ inputs.version }}"
          git push origin ${{ inputs.branch }}
